backend:
  name: github
  repo: PoMkaNik/zar-ptitsa-landing-v2
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
# header
          - {label: Header, name: header, widget: object, collapsed: true, fields: [
              {label: Logo, name: image, widget: image},
              {label: Title, name: title, widget: string},
              {label: Description, name: description, widget: markdown}
          ]}
# reasons
          - {label: Reasons, name: reasons, widget: object, collapsed: true, fields: [
              {label: Title, name: title, widget: string},
              {label: List, name: list, widget: list, fields: [
                {label: Image, name: image, widget: image, required: false},
                {label: "Align Image",  name: "alignImage",  widget: "select",   options: ["left", "center", "right"],  required: false },
                {label: Title, name: title, widget: string, required: false},
                {label: Description, name: description, widget: markdown, required: false},
              ]}
          ]}
# advantages
          - {label: Advantages, name: advantages, widget: object, collapsed: true, fields: [
              {label: Title, name: title, widget: string},
              {label: List, name: list, widget: list, fields: [
                {label: Description, name: description, widget: markdown, required: false},
              ]}
          ]}
# secret
          - {label: Secret, name: secret, widget: object, collapsed: true, fields: [
              {label: Image, name: image, widget: image, required: false},
              {label: "Align Image",  name: alignImage,  widget: "select",   options: ["left", "center", "right"],  required: false },
              {label: Title, name: title, widget: string},
              {label: Description, name: description, widget: markdown, required: false},
              {label: List, name: list, widget: list, fields: [
                {label: Image, name: image, widget: image, required: false},
                {label: "Align Image",  name: "alignImage",  widget: "select",   options: ["left", "center", "right"],  required: false },
                {label: Title, name: title, widget: string, required: false},
                {label: Description, name: description, widget: markdown, required: false},
              ]}
          ]}
# treasure
          - {label: Treasure, name: treasure, widget: object, collapsed: true, fields: [
              {label: Image, name: image, widget: image, required: false},
              {label: "Align Image",  name: alignImage,  widget: "select",   options: ["left", "center", "right"],  required: false },
              {label: Title, name: title, widget: string},
              {label: Description, name: description, widget: markdown, required: false},
              {label: "Type of list",  name: "listType",  widget: "select",   options: ["numbered", "bulleted","none"], default: ['bulleted'] },
              {label: List, name: list, widget: list, fields: [
                {label: Image, name: image, widget: image, required: false},
                {label: "Align Image",  name: "alignImage",  widget: "select",   options: ["left", "center", "right"],  required: false },
                {label: Title, name: title, widget: string, required: false},
                {label: Description, name: description, widget: markdown, required: false},
                {label: Teachers, name: teachers, widget: object, fields: [
                  {label: List, name: list, widget: list, fields: [
                    {label: Image, name: image, widget: image, required: false},
                  ]}
                ]}
              ]}
          ]}
# testimonials
          - {label: Testimonials, name: testimonials, widget: object, collapsed: true, fields: [
              {label: Image, name: image, widget: image, required: false},
              {label: "Align Image",  name: alignImage,  widget: "select",   options: ["left", "center", "right"],  required: false },
              {label: Title, name: title, widget: string},
              {label: Description, name: description, widget: markdown, required: false},
              {label: List, name: list, widget: list, fields: [
                {label: Image, name: image, widget: image, required: false},
                {label: "Align Image",  name: "alignImage",  widget: "select",   options: ["left", "center", "right"],  required: false },
                {label: Author, name: author, widget: string},
                {label: Quote, name: quote, widget: markdown},
              ]}
          ]}
# plans
          - {label: Plans, name: plans, widget: object, collapsed: true, fields: [
              {label: Image, name: image, widget: image, required: false},
              {label: "Align Image",  name: alignImage,  widget: "select",   options: ["left", "center", "right"],  required: false },
              {label: Title, name: title, widget: string},
              {label: Description, name: description, widget: markdown, required: false},
              {label: Plans, name: list, widget: list, fields: [
                {label: Image, name: image, widget: image, required: false},
                {label: "Align Image",  name: "alignImage",  widget: "select",   options: ["left", "center", "right"],  required: false },
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: markdown},
              ]},
              {label: Afterwords, name: afterwords, widget: markdown, required: false},
          ]}
# free lesson
          - {label: Free Lesson, name: freeLesson, widget: object, collapsed: true, fields: [
              {label: Image, name: image, widget: image, required: false},
              {label: "Align Image",  name: alignImage,  widget: "select",   options: ["left", "center", "right"],  required: false },
              {label: Title, name: title, widget: string},
              {label: Description, name: description, widget: markdown, required: false},
              {label: Content, name: list, widget: list, fields: [
                {label: Image, name: image, widget: image, required: false},
                {label: "Align Image",  name: "alignImage",  widget: "select",   options: ["left", "center", "right"],  required: false },
                {label: Title, name: title, widget: string},
                {label: Description, name: description, widget: markdown},
              ]}
          ]}
# form
          - {label: Form Data, name: formData, widget: object, collapsed: true, fields: [
              {label: Image, name: image, widget: image, required: false},
              {label: "Align Image",  name: alignImage,  widget: "select",   options: ["left", "center", "right"],  required: false },
              {label: Title, name: title, widget: string},
              {label: Description, name: description, widget: string, required: false},
              {label: Form Inputs, name: formInputs, widget: list, fields: [
                {label: Input Label, name: inputLabel, widget: string},
                {label: "Input Type",  name: "inputType",  widget: "select",   options: ["text", "phone", "email"], default: ['text'] },
              ]}
          ]}