backend:
  name: github
  repo: PoMkaNik/zar-ptitsa-landing-v2
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img/uploads
public_folder: /img/uploads

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/thank-you.md"
        label: "Thank You Page"
        name: "thank-you"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "thank-you"}
            {label: Image, name: image, widget: image},
            {label: Title, name: title, widget: string},
            {label: Description, name: description, widget: markdown}